apiVersion: v1
kind: Service  #Especificica el recurs a desplegar: Deployment, Service , Pod, etc.
metadata:
     name: serv-pizza # Nom del service que s'ha de crear
spec:
     type: NodePort
     selector:
          app: pods-pizza # Etiquetes identificadores dels Pods dins de ppv-deployment.yaml
     ports:
     - port: 4000 # Port del Service  que es redirigirà cap el port dels Pods.
       targetPort: 80 # Port pel qual els Pods exposen l'aplicació. 
       nodePort: 30000 # Port creat dins de la màquina que es redirigirà cap el port del Service.
